on:
  schedule: 
    - cron:  "0 12 * 1-12 *" 
  workflow_dispatch:
  
name: 01_CoopCred_webscrap_orgaos_estatutarios_bacen.R
  
jobs:
  run-r-script:
    runs-on: ubuntu-latest # use Ubuntu
    env:
      # The GitHub token will be available 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
    steps:
      # imports an action from another repository, 
      # that enables the machine
      # to access the code inside our repository
      - uses: actions/checkout@v3 
      # imports an action from another repository, 
      # that installs R on the machine
      - uses: r-lib/actions/setup-r@v2
        with:
          # uses the RStudio Package Manager
          use-public-rspm: true

        
      # imports an action from another repository, 
      # that deals with the dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          # here we have to add all the packages we used in the script!
          packages: |
            any::gh
            any::dplyr
            any::tidyr
            any::readr
            any::knitr 
            any::httr
            any::glue
            any::janitor
            any::purrr
            any::jsonlite
            any::here
            
      - name: Criar pasta com base no ano e mês
        run: |
          # Obter a data atual em formato yyyy-mm-ddThh:mm:ssZ do GITHUB_SHA
          data_atual_iso8601=${GITHUB_SHA:0:10}

          # Extrair o ano e o mês da data atual
          ano=${data_atual_iso8601:0:4}
          mes=${data_atual_iso8601:5:2}

          # Construir o caminho da pasta
          caminho_pasta="dados/${ano}${mes}"

          # Criar a pasta
          mkdir -p "$caminho_pasta"
                
      - name: Execute Script
        # executes the RScript stored in the file
        # 01-monitoring-quarto-repos/script.R
        run: |
          Rscript "01_CoopCred_webscrap_orgaos_estatutarios_bacen.R"                        

        # save the results in the repository
        # using git in the command line
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
